# Generated by Django 4.2.6 on 2023-10-18 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('avatar', models.CharField(choices=[('Harpers', 'Harpers'), ('Order of the Gauntlet', 'Order of the Gauntlet'), ('Emerald Enclave', 'Emerald Enclave'), ('Lords Alliance', 'Lords Alliance'), ('Zhentarim', 'Zhentarim')], default='Harpers', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picURL', models.CharField(max_length=500)),
                ('race', models.CharField(max_length=100)),
                ('gender', models.CharField(default='Male', max_length=100)),
                ('alignment', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=1)),
                ('exp', models.IntegerField(default=0)),
                ('strength', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.user')),
            ],
        ),
    ]
