# Generated by Django 3.2.12 on 2023-10-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(choices=[('Harpers', 'https://www.dndbeyond.com/avatars/thumbnails/6/340/420/618/636272677995471928.png'), ('Order of the Gauntlet', 'https://www.dndbeyond.com/attachments/thumbnails/5/928/290/504/br-orderofthegauntlet.png'), ('Emerald Enclave', 'https://www.dndbeyond.com/attachments/thumbnails/5/925/290/504/br-emeraldenclave.png'), ('Lords Alliance', 'https://www.dndbeyond.com/attachments/thumbnails/5/926/290/504/br-lordsalliance.png'), ('Zhentarim', 'https://www.dndbeyond.com/attachments/thumbnails/5/927/290/504/br-zhentarim.png')], default='Harpers', max_length=25),
        ),
    ]
