# Generated by Django 4.2.6 on 2023-10-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='charisma',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='character',
            name='constitution',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='character',
            name='wisdom',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='character',
            name='exp',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=15),
        ),
    ]
