# Generated by Django 4.2.6 on 2023-10-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_character_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(default='Male', max_length=100),
        ),
    ]
