# Generated by Django 4.2.6 on 2023-10-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_character_charisma_character_constitution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
