# Generated by Django 3.2.12 on 2023-10-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(choices=[('https://www.dndbeyond.com/attachments/thumbnails/5/924/290/504/br-harpers.png', 'Harpers'), ('https://www.dndbeyond.com/attachments/thumbnails/5/928/290/504/br-orderofthegauntlet.png', 'Order of the Gauntlet'), ('https://www.dndbeyond.com/attachments/thumbnails/5/925/290/504/br-emeraldenclave.png', 'Emerald Enclave'), ('https://www.dndbeyond.com/attachments/thumbnails/5/926/290/504/br-lordsalliance.png', 'Lords Alliance'), ('https://www.dndbeyond.com/attachments/thumbnails/5/927/290/504/br-zhentarim.png', 'Zhentarim')], default='https://www.dndbeyond.com/attachments/thumbnails/5/924/290/504/br-harpers.png', max_length=100),
        ),
    ]
