# Generated by Django 4.2.6 on 2023-10-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_character_exp_alter_character_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(default='Human-M', max_length=20),
        ),
    ]
