# Generated by Django 4.2.6 on 2023-10-17 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_character_race'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='race',
        ),
    ]
